### ISSUE TITLE
Trying to move to jsx

### ISSUE THREAD

**Issue by halcwb** [alfonsogarciacaro/fable-react-sample#2]
I want to move my current app to jsx. 

A first question is how to setup vite such that it serves the index file from the src/Client folder instead of the root folder. For now, I just moved the index file to the root, which works.

See: https://github.com/halcwb/GenPres2/tree/jsx.

Also, my gut feeling is that in the long run using jsx will be much easier to maintain than bindings, what are your thoughts? 

Thanks!!

**Comment by halcwb** [comment]
@alfonsogarciacaro I got it working with vite and I really love the JSX approach! Thank you!!

See: https://github.com/halcwb/GenPres2 how well this works.

**Comment by alfonsogarciacaro** [comment]
Happy to hear it worked for you. Thanks for sharing!
